categoryToApi = {
    'Contact Info': [
        ['CNContactStore', 'enumerateContacts'],
        ['CNContactStore', 'unifiedMeContactWithKeys'],
        ['CNContactStore', 'unifiedContact'],
        ['CNContactStore', 'unifiedContacts'],
        ['CNContactStore', 'defaultContainerIdentifier'],
        ['CNContactStore', 'groups'],
        ['CNContactStore', 'containers'],
        ['CNContactStore', 'CNContactStoreDidChange'],
    ],
    'Health & Fitness': [
        ['HKHealthStore', 'biologicalSex'],
        ['HKHealthStore', 'bloodType'],
        ['HKHealthStore', 'dateOfBirth'],
        ['HKHealthStore', 'dateOfBirthComponents'],
        ['HKHealthStore', 'fitzpatrickSkinType'],
        ['HKHealthStore', 'wheelchairUse'],
        ['HKHealthStore', 'execute'],
        ['HKHealthStore', 'preferredUnits'],
        ['HKHealthStore', 'HKUserPreferencesDidChange'],
        ['HKHealthStore', 'enableBackgroundDelivery'],
        ['HKHealthStore', 'startWatchApp'],
        ['HKHealthStore', 'start'],
        ['HKHealthStore', 'pause'],
        ['HKHealthStore', 'resumeWorkoutSession'],
        ['HKHealthStore', 'activityMoveMode'],
        ['HKAnchoredObjectQuery', 'init'],
        ['HKAnchoredObjectQuery', 'updateHandler'],
    ],
    'Financial Info': [
        ['PKPaymentRequest', 'requiredBillingContactFields'],
        ['PKPaymentRequest', 'requiredShippingContactFields'],
        ['PKPaymentRequest', 'billingContact'],
        ['PKPaymentRequest', 'shippingContact'],
        ['PKPassLibrary', 'passes'],
        ['PKPassLibrary', 'pass'],
        ['PKPassLibrary', 'containsPass'],
        ['PKPassLibrary', 'serviceProviderData'],
        ['PKPassLibrary', 'remoteSecureElementPasses'],
        ['PKPassLibrary', 'canAddFelicaPass'],
        ['PKPassLibrary', 'canAddSecureElementPass'],
        ['PKPassLibrary', 'replacePass'],
        ['PKPassLibrary', 'present'],
        ['PKPassLibrary', 'isSuppressingAutomaticPassPresentation'],
        ['PKPassLibrary', 'requestAutomaticPassPresentationSuppression'],
        ['PKPassLibrary', 'endAutomaticPassPresentationSuppression'],
        ['PKPassLibrary', 'PKSuppressionRequestToken'],
        ['PKPassLibrary', 'openPaymentSetup'],
    ],
    'Location': [
        ['CLLocationManager', 'significantLocationChangeMonitoringAvailable'],
        ['CLLocationManager', 'accuracyAuthorization'],
        ['CLLocationManager', 'isMonitoringAvailable'],
        ['CLLocationManager', 'isRangingAvailable'],
        ['CLLocationManager', 'locationServicesEnabled'],
        ['CLLocationManager', 'headingAvailable'],
        ['CLLocationManager', 'regionMonitoringAvailable'],
        ['CLLocationManager', 'regionMonitoringEnabled'],
        ['CLLocationManager', 'startUpdatingLocation'],
        ['CLLocationManager', 'requestLocation'],
        ['CLLocationManager', 'allowsBackgroundLocationUpdates'],
        ['CLLocationManager', 'showsBackgroundLocationIndicator'],
        ['CLLocationManager', 'startMonitoringSignificantLocationChanges'],
        ['CLLocationManager', 'startUpdatingHeading'],
        ['CLLocationManager', 'startMonitoring'],
        ['CLLocationManager', 'requestState'],
        ['CLLocationManager', 'startRangingBeacons'],
        ['CLLocationManager', 'startMonitoringVisits'],
        ['CLLocationManager', 'location'],
        ['CLLocationManager', 'heading'],
        ['CLVisit', 'coordinate'],
        ['CLVisit', 'horizontalAccuracy'],
        ['CLVisit', 'arrivalDate'],
        ['CLVisit', 'departureDate'],
    ],
    'User Content': [
        ['ILMessageFilterQueryHandling', 'handle'],
        ['PHPhotoLibrary', 'shared'],
        ['PHPhotoLibrary', 'register'],
        ['PHAsset', 'fetchAssets'],
        ['PHAssetCollection', 'fetchAssetCollections'],
        ['PHAssetCollection', 'fetchMoments'],
        ['PHCollection', 'fetchCollections'],
        ['PHCollection', 'fetchTopLevelUserCollections'],
        ['PHCollectionList', 'fetchCollectionListsContaining'],
        ['PHCollectionList', 'fetchCollectionLists'],
        ['PHCollectionList', 'fetchMomentLists'],
        ['AVAudioRecorder', 'record'],
        ['AudioQueueServices', 'AudioQueueNewInput'],
        ['AudioQueueServices', 'AudioQueueStart'],
    ],
    'Identifiers': [
        ['UIDevice','current'],
        ['UIDevice','UIDevicecurrentDevice'],
        ['DCDevice','current']
    ]
}
